version: '3.8'

services:
  frontend:
    image: hcalsan/bigfoot-frontend:latest
    container_name: bigfoot-frontend
    restart: always
    ports:
      - "80:4321"
    networks:
      - postgres_net

  backend:
    image: hcalsan/bigfoot-backend:latest
    container_name: bigfoot-backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - bigfoot_uploads:/app/public/uploads
    networks:
      - postgres_net

networks:
  postgres_net:
    external: true