FROM node:20-alpine

# Instalar herramientas
RUN apk add --no-cache libc6-compat openssl

WORKDIR /app

# Instalar dependencias
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

# Copiar código fuente
COPY . .
RUN rm -rf public/uploads/productos/*.ts

# Build de Astro
RUN pnpm build

ENV NODE_ENV=production
EXPOSE 4321

CMD ["pnpm", "preview", "--host"]
