import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export async function seedMontañasYRutas() {
  const montanas = [
    {
      nombre: 'Baqueira Beret',
      ubicacion: 'Pirineos',
      altura: 2610,
      descripcion: 'Una de las estaciones más grandes y populares de España.',
      latitud: 42.7,
      longitud: 0.9333,
      rutas: [
        { nombre: 'Bosque', dificultad: 'fácil', longitud: 2.8 },
        { nombre: 'Era Coma', dificultad: 'fácil', longitud: 3.0 },
        { nombre: 'Pales der Arias', dificultad: 'fácil', longitud: 2.2 },
        { nombre: 'Esquirós', dificultad: 'media', longitud: 3.5 },
        { nombre: 'Dera Cascada', dificultad: 'media', longitud: 3.8 },
        { nombre: 'Luis Arias', dificultad: 'difícil', longitud: 2.4 },
        { nombre: 'Manaud', dificultad: 'difícil', longitud: 2.6 },
        { nombre: 'Ticolet', dificultad: 'experto', longitud: 2.3 },
        { nombre: 'Escornacrabes', dificultad: 'experto', longitud: 2.1 },
      ],
    },
    {
      nombre: 'Formigal',
      ubicacion: 'Pirineos',
      altura: 2250,
      descripcion: 'Estación aragonesa con gran variedad de pistas.',
      latitud: 42.7769,
      longitud: -0.3592,
      rutas: [
        { nombre: 'Debutantes Portalet', dificultad: 'fácil', longitud: 1.9 },
        { nombre: 'Cantal', dificultad: 'fácil', longitud: 2.4 },
        { nombre: 'Anayet', dificultad: 'media', longitud: 3.1 },
        { nombre: 'Collado', dificultad: 'media', longitud: 2.9 },
        { nombre: 'Sarrios', dificultad: 'media', longitud: 2.6 },
        { nombre: 'Tres Hombres', dificultad: 'difícil', longitud: 2.5 },
        { nombre: 'Canal Roya', dificultad: 'difícil', longitud: 2.8 },
        { nombre: 'Garmet', dificultad: 'experto', longitud: 2.7 },
        { nombre: 'Escarra', dificultad: 'experto', longitud: 2.2 },
      ],
    },
    {
      nombre: 'Cerler',
      ubicacion: 'Pirineos',
      altura: 2630,
      descripcion: 'La estación más alta del Pirineo aragonés.',
      latitud: 42.5905,
      longitud: 0.5409,
      rutas: [
        { nombre: 'Camino del Sarrau', dificultad: 'fácil', longitud: 3.0 },
        { nombre: 'Ampriu', dificultad: 'fácil', longitud: 2.5 },
        { nombre: 'Cogulla', dificultad: 'media', longitud: 3.5 },
        { nombre: 'Robellons', dificultad: 'media', longitud: 3.0 },
        { nombre: 'El Bosque', dificultad: 'media', longitud: 2.7 },
        { nombre: 'Gallinero', dificultad: 'difícil', longitud: 3.1 },
        { nombre: 'Canal Amplia', dificultad: 'difícil', longitud: 2.6 },
        { nombre: 'Basibé', dificultad: 'experto', longitud: 2.8 },
        { nombre: 'Tuca Blanca', dificultad: 'experto', longitud: 2.3 },
      ],
    },
    {
      nombre: 'Boí Taüll',
      ubicacion: 'Pirineos',
      altura: 2750,
      descripcion: 'Ideal para esquiadores avanzados.',
      latitud: 42.51,
      longitud: 0.85,
      rutas: [
        { nombre: 'Pastors', dificultad: 'fácil', longitud: 2.4 },
        { nombre: 'Vaques', dificultad: 'fácil', longitud: 2.9 },
        { nombre: 'Cap del Puig', dificultad: 'media', longitud: 3.3 },
        { nombre: 'Raspes Roies', dificultad: 'media', longitud: 3.0 },
        { nombre: 'La Serra', dificultad: 'difícil', longitud: 2.7 },
        { nombre: 'Cinta Bonabé', dificultad: 'difícil', longitud: 2.6 },
        { nombre: 'Coll de Roies', dificultad: 'experto', longitud: 2.9 },
        { nombre: 'La Coma', dificultad: 'experto', longitud: 2.8 },
      ],
    },
    {
      nombre: 'Navacerrada',
      ubicacion: 'Sistema Central',
      altura: 2177,
      descripcion: 'Estación cercana a Madrid con encanto.',
      latitud: 40.7291,
      longitud: -4.0169,
      rutas: [
        { nombre: 'El Bosque', dificultad: 'fácil', longitud: 1.8 },
        { nombre: 'Telégrafo', dificultad: 'fácil', longitud: 2.0 },
        { nombre: 'Tubo', dificultad: 'media', longitud: 2.0 },
        { nombre: 'Guarramillas', dificultad: 'media', longitud: 2.3 },
        { nombre: 'Embudo', dificultad: 'difícil', longitud: 1.7 },
        { nombre: 'Tubo del Escaparate', dificultad: 'experto', longitud: 2.0 },
        { nombre: 'Pluviómetro', dificultad: 'experto', longitud: 1.9 },
      ],
    },
    {
      nombre: 'Valdesquí',
      ubicacion: 'Sistema Central',
      altura: 2280,
      descripcion: 'Otra opción popular cerca de Madrid.',
      latitud: 40.799,
      longitud: -3.9719,
      rutas: [
        { nombre: 'Valcotos', dificultad: 'fácil', longitud: 2.1 },
        { nombre: 'Zetas', dificultad: 'fácil', longitud: 2.4 },
        { nombre: 'Pradera', dificultad: 'media', longitud: 2.7 },
        { nombre: 'Peñalara', dificultad: 'media', longitud: 3.4 },
        { nombre: 'El Collado', dificultad: 'difícil', longitud: 2.6 },
        { nombre: 'Tubo de Valdemartín', dificultad: 'experto', longitud: 2.7 },
        { nombre: 'Testero', dificultad: 'experto', longitud: 2.5 },
      ],
    },
    {
      nombre: 'San Isidro',
      ubicacion: 'Cordillera Cantábrica',
      altura: 2020,
      descripcion: 'Estación leonesa con pistas variadas.',
      latitud: 43.0648,
      longitud: -5.3699,
      rutas: [
        { nombre: 'Debutantes', dificultad: 'fácil', longitud: 1.9 },
        { nombre: 'Cebolledo', dificultad: 'fácil', longitud: 2.2 },
        { nombre: 'Requejines', dificultad: 'media', longitud: 2.8 },
        { nombre: 'Salencias', dificultad: 'media', longitud: 3.1 },
        { nombre: 'Peña del Sol', dificultad: 'difícil', longitud: 2.2 },
        { nombre: 'Las Lomas', dificultad: 'difícil', longitud: 2.4 },
        { nombre: 'El Toneo', dificultad: 'experto', longitud: 2.6 },
        { nombre: 'La Solana', dificultad: 'experto', longitud: 2.3 },
      ],
    },
    {
      nombre: 'Leitariegos',
      ubicacion: 'Cordillera Cantábrica',
      altura: 1800,
      descripcion: 'Pequeña estación familiar.',
      latitud: 43.0,
      longitud: -6.4167,
      rutas: [
        { nombre: 'La Mora', dificultad: 'fácil', longitud: 1.5 },
        { nombre: 'Brezal', dificultad: 'fácil', longitud: 2.2 },
        { nombre: 'El Cerezal', dificultad: 'media', longitud: 2.0 },
        { nombre: 'La Laguna', dificultad: 'difícil', longitud: 1.8 },
        { nombre: 'La Falla', dificultad: 'difícil', longitud: 2.0 },
        { nombre: 'Tubo de la Laguna', dificultad: 'experto', longitud: 2.0 },
        { nombre: 'Cornón', dificultad: 'experto', longitud: 1.9 },
      ],
    },
    {
      nombre: 'Sierra Nevada',
      ubicacion: 'Granada',
      altura: 3398,
      descripcion: 'La estación más meridional de Europa.',
      latitud: 37.0916,
      longitud: -3.3988,
      rutas: [
        { nombre: 'El Águila', dificultad: 'fácil', longitud: 6.0 },
        { nombre: 'Borreguiles', dificultad: 'fácil', longitud: 3.5 },
        { nombre: 'Veleta', dificultad: 'media', longitud: 5.2 },
        { nombre: 'Laguna', dificultad: 'media', longitud: 3.7 },
        { nombre: 'Loma de Dílar', dificultad: 'difícil', longitud: 3.6 },
        { nombre: 'Zahareña', dificultad: 'difícil', longitud: 4.0 },
        { nombre: 'Tajos de la Virgen', dificultad: 'experto', longitud: 3.2 },
        { nombre: 'Tubo del Veleta', dificultad: 'experto', longitud: 2.9 },
        { nombre: 'San Juan', dificultad: 'experto', longitud: 2.5 },
      ],
    },
  ];

  for (const montana of montanas) {

    const createdMontana = await prisma.montaña.create({
      data: {
        nombre: montana.nombre,
        ubicacion: montana.ubicacion,
        altura: montana.altura,
        descripcion: montana.descripcion,
        lat: montana.latitud,
        lon: montana.longitud,
        rutas: {
          create: montana.rutas,
        },
      },
    });
    console.log(`✅ Montaña creada: ${createdMontana.nombre}`);
  }
}
