name: CI/CD

on:
  pull_request:
    types: [opened, reopened,synchronize]

jobs:
  build-and-push-image:
    uses: ./.github/workflows/reusable-build-push.yaml
    with:
      image_frontend: bigfoot-frontend
      image_backend: bigfoot-backend
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  despliegue:
    needs: build-and-push-image
    uses: ./.github/workflows/build-despligue_CI_&_CD.yaml
    with:
      image_frontend_tag: ${{ needs.build-and-push-image.outputs.tag_frontend }}
      image_backend_tag: ${{ needs.build-and-push-image.outputs.tag_backend }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      HOST: ${{ secrets.HOST }}
      USER: ${{ secrets.USER }}
