name: Reutilizable para build & push

on:
  workflow_call:
    inputs:
      image_frontend:
        required: true
        type: string
      image_backend:
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true
    outputs:
      tag_frontend:
        description: "Tag del frontend generado"
        value: ${{ jobs.build-and-push.outputs.tag_frontend }}
      tag_backend:
        description: "Tag del backend generado"
        value: ${{ jobs.build-and-push.outputs.tag_backend }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag_frontend: ${{ steps.tag_frontend.outputs.tag }}
      tag_backend: ${{ steps.tag_backend.outputs.tag }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Extraer la versión de la imagen
        id: img_version
        shell: bash
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Obtener tag frontend
        id: tag_frontend
        uses: ./.github/tag_imagen
        with:
          image_name: ${{ inputs.image_frontend }}
          version: ${{ steps.img_version.outputs.version }}
        env:
          USERNAME: ${{ vars.DOCKER_USERNAME }}

      - name: Obtener tag backend
        id: tag_backend
        uses: ./.github/tag_imagen
        with:
          image_name: ${{ inputs.image_backend }}
          version: ${{ steps.img_version.outputs.version }}
        env:
          USERNAME: ${{ vars.DOCKER_USERNAME }}

      - name: Login a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push frontend
        run: |
          docker build -f Dockerfile.frontend -t ${{ inputs.image_frontend }}:latest .
          docker tag ${{ inputs.image_frontend }}:latest ${{ steps.tag_frontend.outputs.tag }}
          docker push ${{ steps.tag_frontend.outputs.tag }}

      - name: Build & Push backend
        run: |
          docker build -f Dockerfile.backend -t ${{ inputs.image_backend }}:latest .
          docker tag ${{ inputs.image_backend }}:latest ${{ steps.tag_backend.outputs.tag }}
          docker push ${{ steps.tag_backend.outputs.tag }}
